### ISSUE TITLE
login: add a way to provide the password from stdin

### ISSUE THREAD

**Issue by tormath1** [cycloidio/cycloid-cli#10]
the current way to pass the password is from the flag `--password 1234`. We should be able to pass the password from stdin.
```shell
--password | echo my-password
--password | cat ./my-password
```

an example of this feature can be found here:
https://github.com/cycloidio/inframap/blob/173f4eb7fdba6b1ebc64dfc0793b18e0a877ff3d/cmd/root.go#L29-L32

**Comment by gaelL** [comment]
the code changed quite a lot and now we use API_KEY env var
