### ISSUE TITLE
errors: define a better error handling

### ISSUE THREAD

**Issue by tormath1** [cycloidio/cycloid-cli#11]
we are currently doing this:

```go
return err
```

or in the best case

```go
return errors.Wrap(err, "unable to ...")
```

We should find a way to display properly the errors generated by swagger and generated by the CLI himself to guide the user in its debugging.

**Comment by gaelL** [comment]
Update adding a standard error to reproduce details not displayed:

.1 create an org containing a project
.2 try to delete the org

The CLI currently display only

```
Error: unable to delete organization: [DELETE /organizations/{organization_canonical}][409] deleteOrg default &{Errors:[0xc000488240]}
```

The API send a 409 error with this payload:

```
{"errors":[{"code":"ConflictDeletingOrgHasProjects","message":"organization cannot be deleted because it has some projects","details":["Projects should be deleted in order to delete the organization"]}]}
```
