### ISSUE TITLE
Bootstrap a stack feature

### ISSUE THREAD

**Issue by gaelL** [cycloidio/cycloid-cli#86]
An idea would simplify the creation of the skeleton of a stack by using the CLI to bootstrap the git.

Ideally we would expect the CLI bootstrap to ask few questions such :
  * Cloud provider
  * Using Terraform
  * Using ansible

Then regarding this generate a stack based on Pipelines templates, terraform sample files/modules and a .forms.yaml

**Comment by xescugc** [comment]
I would consider checking what the BE is doing to copy the same logic as this what it's done when the user uses StackCraft and creates a Stack at the end.

And if it could be abstracted it could be imported as a lib on the CLI and the BE (maybe too much though hehe but would be really good).

**Comment by gaelL** [comment]
closing, this has been implemented directly in our product
